name: Robot Framework API Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    env:
      ENV: dev                # usado pelos testes Robot
      PROJECT_KEY: SCRUM      # Jira project key (Zephyr Scale usa a mesma key)

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Se .env.example existir, copia; caso contrário cria um .env mínimo
      - name: Preparar .env
        shell: bash
        run: |
          if [ -f ".env.example" ]; then
            cp .env.example .env
            echo "Usando .env a partir de .env.example"
          else
            echo "ENV=dev" > .env
            # Exemplo: echo "API_BASE_URL=https://reqres.in" >> .env
            echo "Criado .env mínimo (sem .env.example)"
          fi
          echo "Conteúdo do .env:"
          cat .env

      - name: Executar testes Robot Framework (gera JUnit)
        run: |
          mkdir -p reports
          robot -d reports -x junit.xml tests/api

      - name: Upload JUnit para Zephyr Scale (sempre)
        if: always()
        env:
          ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
          PROJECT_KEY: ${{ env.PROJECT_KEY }}
        run: |
          if [ ! -f "reports/junit.xml" ]; then
            echo "reports/junit.xml não encontrado. Pulando upload para Zephyr."
            exit 0
          fi
          echo "Enviando junit.xml para Zephyr Scale (projectKey=${PROJECT_KEY})..."
          curl -sS -X POST \
            -H "Authorization: Bearer ${ZEPHYR_TOKEN}" \
            -F "file=@reports/junit.xml;type=application/xml" \
            "https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey=${PROJECT_KEY}&autoCreateTestCases=true" \
            || { echo 'Falha no upload para Zephyr Scale'; exit 1; }

      - name: Publicar Relatórios Robot Framework (sempre)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: |
            reports/
            reports/log.html
            reports/report.html
            reports/output.xml
